CI: use sudo, assume docker present, use diff-{quality,cover}
Huh. I kinda just assumed we'd be root. Guess not!

Docker is already in the GHA base image, no need to install.

Both linter tools report issues on the current master branch,
which means they will always fail on exit. Using diff-quality
gives us a check we can usefully fail on (as configured in this
PR, it will only fail if the quality of the lines changed in
the PR is less than 9.0).

Similarly we can generate a coverage report and use diff-cover
to fail if coverage of the PR is under 90%.

This also uses a standard configuration file name for the pylint
config (so we don't have to specify it with `--rcfile`), removes
all non-default settings from the pylint config so it's clearer
what we really intend to configure, and moves the flake8 config
to a config file like pylint.

We don't use pyproject.toml for configuration here because GHA's
Ubuntu environment is just not new enough, the tools in it don't
consistently read from pyproject.toml.

Signed-off-by: Adam Williamson <awilliam@redhat.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,10 +11,23 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      - name: Install make and docker
-        run: apt-get install make docker docker.io
+      - name: Install required packages
+        run: sudo apt-get install make flake8 pylint
+      # it's not in Ubuntu 22.04, was added in 23.04
+      - name: Install diff-cover from pip
+        run: pip install diff-cover
       - name: Run the tests
-        run: make container-unittests-fedora
+        run: sudo make container-unittests-fedora
+      - name: Run diff-cover
+        run: diff-cover coverage.xml  --compare-branch=origin/$GITHUB_BASE_REF --fail-under=90
+      - name: Run diff-quality (pylint)
+        # we want to run this regardless of whether previous lint steps failed
+        if: success() || failure()
+        run: diff-quality --compare-branch=origin/$GITHUB_BASE_REF --violations=pylint --fail-under=90
+      - name: Run diff-quality (flake8)
+        # we want to run this regardless of whether previous lint steps failed
+        if: success() || failure()
+        run: diff-quality --compare-branch=origin/$GITHUB_BASE_REF --violations=flake8 --fail-under=90
   unittests-el7:
     runs-on: ubuntu-latest
     steps:
@@ -22,20 +35,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      - name: Install make and docker
-        run: apt-get install make docker
+      - name: Install make
+        run: sudo apt-get install make
       - name: Run the tests
-        run: make container-unittests-el7
-  lint:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout the repo
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Install make, pylint and flake8
-        run: apt-get install make pylint flake8
-      - name: Run pylint
-        run: make pylint
-      - name: Run flake8
-        run: make flake8
+        run: sudo make container-unittests-el7
